const fs = require('fs');
const p = 'C:/Users/natso/OneDrive/Desktop/Sirvya/Fitlek/lib/screens/ENG/workout_webview.dart';
let c = '';
c += "import 'dart:async';\n";
c += "import 'dart:convert';\n";
c += "import 'package:firebase_auth/firebase_auth.dart';\n";
c += "import 'package:flutter/foundation.dart';\n";
c += "import 'package:flutter/material.dart';\n";
c += "import 'package:http/http.dart' as http;\n";
c += "import 'package:webview_flutter/webview_flutter.dart' show NavigationDelegate, JavaScriptMode, WebViewController, WebViewWidget;\n";
c += "import '../../constants/urls.dart';\n";
c += "import '../../services/apiService.dart';\n";
c += "import '../../services/google_auth_service.dart';\n";
c += "import '../../theme/fitlek_theme_extension.dart';\n";
c += "class WorkoutWebviewScreen extends StatefulWidget { final String? serverBase; const WorkoutWebviewScreen({super.key, this.serverBase}); @override State<WorkoutWebviewScreen> createState() => _WorkoutWebviewState(); }\n";
c += "class _WorkoutWebviewState extends State<WorkoutWebviewScreen> {\n";
c += "  static final Duration _timeout = const Duration(seconds: 20);\n";
c += "  final WebViewController _controller = WebViewController();\n";
c += "  String? _sessionToken; bool _loading = true; bool _needSignIn = false; String? _error;\n";
c += "  String get _base => widget.serverBase ?? workoutBaseUrl;\n";
c += "  @override void initState() { super.initState(); unawaited(_signInAndRun()); }\n";
c += "  Future<void> _signInAndRun() async {\n";
c += "    try {\n";
c += "      final user = FirebaseAuth.instance.currentUser;\n";
c += "      if (user == null) { if (mounted) setState(() => _needSignIn = true); return; }\n";
c += "      final idToken = await user.getIdToken();\n";
c += "      final res = await http.post(Uri.parse(_base + '/api/auth/sirvya-login'), headers: {'Content-Type': 'application/json'}, body: jsonEncode({'token': idToken})).timeout(_timeout);\n";
c += "      if (!mounted) return;\n";
c += "      final data = jsonDecode(res.body);\n";
c += "      if (res.statusCode == 200) {\n";
c += "        final token = data['token'] as String?;\n";
c += "        if (token == null || token.isEmpty) { setState(() => _error = 'No session token'); return; }\n";
c += "        _sessionToken = token;\n";
c += "        unawaited(ApiService.setSirvyaAuth(token));\n";
c += "        final frag = Uri.encodeComponent(token);\n";
c += "        _controller.setJavaScriptMode(JavaScriptMode.unrestricted);\n";
c += "        _controller.setNavigationDelegate(NavigationDelegate(onPageFinished: (_) => setState(() => _loading = false)));\n";
c += "        unawaited(_controller.loadRequest(Uri.parse(_base + '/#sirvya_token=' + frag)));\n";
c += "        setState(() => _loading = true);\n";
c += "      } else { setState(() => _error = 'Login failed: ' + (data['message'] ?? data['error'] ?? 'HTTP ' + res.statusCode)); }\n";
c += "    } catch (e) { if (mounted) setState(() => _error = 'Login error: ' + e.toString()); }\n";
c += "  }\n";
c += "  Future<void> _signInWithSirvya() async {\n";
c += "    try { await GoogleAuthService.signInWithGoogle(role: 'client'); if (mounted) setState(() => _needSignIn = false); unawaited(_signInAndRun()); }\n";
c += "    catch (e) { if (mounted) setState(() => _error = 'Google sign-in failed: ' + e.toString()); }\n";
c += "  }\n";
c += "  Widget _buildTopBar(BuildContext context) { return IconButton(icon: const Icon(Icons.arrow_back), onPressed: () => Navigator.of(context).maybePop()); }\n";
c += "  @override Widget build(BuildContext context) {\n";
c += "    final view = WebViewWidget(controller: _controller);\n";
c += "    return Scaffold(backgroundColor: Theme.of(context).scaffoldBackgroundColor, appBar: AppBar(leading: _buildTopBar(context)), body: Column(children: [Expanded(child: Stack(children: [view, if (_needSignIn) _buildSignIn(context) else if (_error != null && _sessionToken == null) _buildError(context) else if (_loading) Center(child: CircularProgressIndicator(color: Theme.of(context).colorScheme.primary))]))]));\n";
c += "  }\n";
c += "  Widget _buildSignIn(BuildContext context) { return Expanded(child: Center(child: Text('Connect your SIRVYA account to train.', style: TextStyle(fontSize: 17))));\n";
c += "  }\n";
c += "  Widget _buildError(BuildContext context) { return Expanded(child: Center(child: Text(_error ?? 'Error', style: TextStyle(fontSize: 13))));\n";
c += "  }\n";
c += "}\n";
fs.writeFileSync(p, c);
console.log('OK', c.split('\n').length);