name: fitlek
description: Fitlek - Premium Fitness Coach App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  http: ^1.2.1
  http_parser: ^4.0.2
  shared_preferences: ^2.3.2
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
