const fs = require('fs');
const p = 'C:/Users/natso/OneDrive/Desktop/Sirvya/Fitlek/lib/screens/ENG/workout_webview.dart';
let c = '';
c += "import 'dart:async';\n";
c += "import 'dart:convert';\n";
c += "import 'package:firebase_auth/firebase_auth.dart';\n";
c += "import 'package:flutter/foundation.dart';\n";
c += "import 'package:flutter/material.dart';\n";
c += "import 'package:http/http.dart' as http;\n";
c += "import 'package:webview_flutter/webview_flutter.dart' show NavigationDelegate, JavaScriptMode, WebViewController, WebViewWidget;\n";
c += "import '../../constants/urls.dart';\n";
c += "import '../../services/apiService.dart';\n";
c += "import '../../services/google_auth_service.dart';\n";
c += "import '../../theme/fitlek_theme_extension.dart';\n";
c += "\n";
c += "class WorkoutWebviewScreen extends StatefulWidget {\n";
c += "  final String? serverBase;\n";
c += "  const WorkoutWebviewScreen({super.key, this.serverBase});\n";
c += "  @override\n";
c += "  State<WorkoutWebviewScreen> createState() => _WorkoutWebviewState();\n";
c += "}\n";
c += "\n";
c += "class _WorkoutWebviewState extends State<WorkoutWebviewScreen> {\n";
c += "  static final Duration _timeout = const Duration(seconds: 20);\n";
c += "  final WebViewController _controller = WebViewController();\n";
c += "  String? _sessionToken;\n";
c += "  bool _loading = true;\n";
c += "  bool _needSignIn = false;\n";
c += "  String? _error;\n";
c += "  String get _base => widget.serverBase ?? workoutBaseUrl;\n";
c += "\n";
c += "  @override\n";
c += "  void initState() { super.initState(); unawaited(_signInAndRun()); }\n";
c += "\n";
c += "  Future<void> _signInAndRun() async {\n";
c += "    try {\n";
c += "      final user = FirebaseAuth.instance.currentUser;\n";
c += "      if (user == null) { if (mounted) setState(() => _needSignIn = true); return; }\n";
c += "      final idToken = await user.getIdToken();\n";
c += "      final res = await http.post(\n";
c += "        Uri.parse(_base + '/api/auth/sirvya-login'),\n";
c += "        headers: {'Content-Type': 'application/json'},\n";
c += "        body: jsonEncode({'token': idToken}),\n";
c += "      ).timeout(_timeout);\n";
c += "      if (!mounted) return;\n";
c += "      final data = jsonDecode(res.body);\n";
c += "      if (res.statusCode == 200) {\n";
c += "        final token = data['token'] as String?;\n";
c += "        if (token == null || token.isEmpty) { setState(() => _error = 'No session token'); return; }\n";
c += "        _sessionToken = token;\n";
c += "        unawaited(ApiService.setSirvyaAuth(token));\n";
c += "        final frag = Uri.encodeComponent(token);\n";
c += "        _controller.setJavaScriptMode(JavaScriptMode.unrestricted);\n";
c += "        _controller.setNavigationDelegate(NavigationDelegate(\n";
c += "          onPageFinished: (_) => setState(() => _loading = false),\n";
c += "        ));\n";
c += "        unawaited(_controller.loadRequest(Uri.parse(_base + '/#sirvya_token=' + frag)));\n";
c += "        setState(() => _loading = true);\n";
c += "      } else {\n";
c += "        setState(() => _error = 'Login failed: ' + (data['message'] ?? data['error'] ?? 'HTTP ' + res.statusCode));\n";
c += "      }\n";
c += "    } catch (e) { if (mounted) setState(() => _error = 'Login error: ' + e.toString()); }\n";
c += "  }\n";
c += "\n";
c += "  Future<void> _signInWithSirvya() async {\n";
c += "    try {\n";
c += "      await GoogleAuthService.signInWithGoogle(role: 'client');\n";
c += "      if (mounted) setState(() => _needSignIn = false);\n";
c += "      unawaited(_signInAndRun());\n";
c += "    } catch (e) { if (mounted) setState(() => _error = 'Google sign-in failed: ' + e.toString()); }\n";
c += "  }\n";
c += "\n";
c += "  Widget _buildTopBar(BuildContext context) {\n";
c += "    return IconButton(icon: const Icon(Icons.arrow_back), onPressed: () => Navigator.of(context).maybePop());\n";
c += "  }\n";
fs.appendFileSync(p, c);
console.log('Part 1 written');