// Record reviewed recovery work without regenerating or replacing historical audits.
import fs from 'node:fs';
const auditPath=new URL('../../docs/WORKOUT_RECOVERY_CURRENT.md',import.meta.url);
const old=fs.readFileSync(auditPath,'utf8');
const accepted='EXACT / ACCEPTABLE PARITY';
const updates=new Map();
const update=(name,implementation,test,status,visual,flow,source,behavior)=>updates.set(name,{implementation,test,status,visual,flow,source,behavior});
update('Workout navigation','Five tabs, centered 560 px maximum bar and orange Resume; SIRVYA opens the module full screen on demand, with explicit Back to SIRVYA. One nested Workout navigator retains the active session/timer.', 'Full host entry/return test and release-browser fixture check; existing cross-tab timer/Resume tests. Browser checks Plan, Stats and Exercises without host navigation.',accepted);
update('Home hierarchy','Source week/Today, historical weight/goal and streak hierarchy retained. Native Home has an additional recent-workout/tools area. Date selection, weight/chart spacing and chart rendering remain visibly different.','Matched 396/1100 captures reviewed; Home flow and responsive tests pass. Full built-app fixture also renders without duplicated navigation.');
update('Week strip','Browsable week, today/planned/completed/override markers and date override entry. Native rectangular selected-day styling still differs from the source circle.','Week navigation/date fixtures and source/native Home captures reviewed.');
update('Today state','Retained active session takes precedence; direct Start/Resume and dated routine/rest context. Native Today typography/action badge differs from source.','Start/Resume/navigation tests and matched Home captures.');
update('Home weight/check-in','Latest historical daily reading, goal/direction-aware delta, Log and 30-point chronological chart. Native typography, dates, axes and goal/chart spacing differ.','Daily projection/goal/check-in tests and matched Home/check-in captures; no account-field substitution.');
update('Home streak/activity','Week-based grace/streak/counts open the month calendar. Calendar displays actual monthly workout count, duration and volume plus trained/planned/rescheduled markers. Native day surfaces/spacing differ.','Monthly fixture asserts one workout, 30 minutes and 2900 kg; trained/date navigation and paired calendar captures.');
update('Plan screen/week assignment','Reusable routines and recurring weekday assignments remain separate. Weekday sheet saves/closes on tapping routine or rest. Native combined-day extension is behind More planning options; desktop columns retained. Main grouped week rows still differ from source individual cards.','One-tap weekday PUT and immediate dismissal asserted; MySQL weekly invariance and paired Plan/assignment captures.');
update('Date overrides/rescheduling','One-tap routine/rest saves and closes the date sheet; reset removes only the override. Base recurring assignments remain intact; More planning options retains combined-day extension.','One-tap date PUT and dismissal; MySQL save/reset/base-week invariance and paired override captures.');
update('Move Monday to Tuesday','Native atomic move sets source rest and destination routine in one transaction without changing the recurring week; source itself offers two independent date overrides.','MySQL atomic move/rollback and base-week invariance; distinct native move interaction is an additional flow.');
update('Routine create/edit/save','Personal routine live autosave/retry retains IDs/revisions. Editable white name field, progression badge, individual exercise cards and muscle preview replace the extra editor app bar. Native progression/exercise rows remain taller; Coach explicit save is preserved.','Autosave failure/retry/stable-ID tests; responsive and paired editor captures.');
update('Exercise configuration','Compact sets/reps/time/load steppers, bodyweight/per-side choices and Cupertino mode segments; prescription/progression/rest persist. Additional Coach controls remain under advanced options. Native sheet spacing/control glyphs still differ.','Mode/per-side/odd-target guards, retained picker Cancel/Save, Coach assignment and 320/396/1100 responsive/capture checks.');
update('Routine muscle preview','Live planned effective sets use bundled MIT source anatomy contours with selectable front/back figures. Preview is in What this session hits card with top-six muscle chips. Taller native editor rows place some chips below the first viewport.','Four-view contour/hit tests, responsive coverage and matched editor captures.');
update('Library result rows','Individual white rounded thumbnail cards, title-cased name/target/equipment, best load and tinted direct Plan action; results and filters scroll together. Native detail route is assessed separately.','Matched 396/1100 Library captures reviewed; direct add-to-routine/library and landscape/enlarged-text tests.',accepted,'Individual rounded white result cards, thumbnail and tinted Plan action');
update('Library pagination/loading/empty','Library pages are 40 records and picker pages 50; Show more, reset on search/filter, loading/error/no-match retained. A full 50-to-100 picker boundary interaction has not been asserted.','API/library/recovery suites pass; boundary interaction remains an available verification gap.');
update('Custom exercise create','Name/body-part chips and optional description create a stable private exercise, with search prefill; richer metadata is behind More exercise options. Cardio body part infers duration/speed mode.','Minimal custom/cardio creation/selection widgets, MySQL duplicates/ownership/lifecycle and paired custom captures reviewed.',accepted);
update('Pre-workout weigh-in','Bounded content-height sheet with prominent 48 px numeric weight, circular +/- controls, quick adjustments, slider, full-width Save and start, Skip and Choose another. Latest historical reading and same-day update retained.','Save/skip/cancel/local-date/goal tests; matched 396/1100 check-in captures reviewed.',accepted);
update('Guided exercise view','Focused exercise/superset unit, actual previous values, target/progression, grid and navigation retained. Circular pending/completed controls are aligned; bundled licensed replacements cover only part of catalog. Header/grid spacing remains visibly different.','Focused/mode/timer/superset tests and matched Active captures; full media limitation is separately license-blocked.');
update('Set completion/undo/add/remove','Compact steppers and circular pending/completed buttons, undo and direct add/remove footer with duplicate-last prefill; actual execution revisions/drafts retained. Native table spacing differs.','Logging/undo/revision/idempotency/structural tests, refreshed Active captures and prior 29 affected-suite passes.');
update('Completion summary','Locked 300 px centered white dialog, trophy/title, four actual metrics, separate load/e1RM records, source MIT trained-muscle figures and explicit green Nice! return. Native backdrop lacks source blur; no implicit dismissal.','Matched one-set/600 kg/30-minute summary at 396/1100 reviewed; locked-summary/explicit Home return and enlarged-text tests.',accepted);
update('Rest wall-clock/background','One global persisted deadline, timestamp catch-up and rescheduling. Android uses exactAllowWhileIdle when permission exists, otherwise inexact fallback; explicit Workout permission button and reboot receiver added. Physical delivery/process-kill behavior remains unverified.','Timestamp jump/restore/reminder tests and code analysis pass. No attached device; notification/sound/vibration/awake/process-kill checks deferred.');
update('History','34 px title/count and compact single-line date/duration/sets/volume rows aligned with source. Actual mode-aware detail/delete/edit and Coach comparison retained; native detail route still differs and lacks paired detail capture.','MySQL history lifecycle, native review tests and paired History list captures.');
update('Stats overview','Compact 78 px source metric tiles, direction-aware 30-day weight delta, timestamped 53-week heatmap, segmented periods and front/back maps; wide two-column charts and recent history retained. Native chart and lower analytic-card styling remains different.','Matched Stats captures, aggregate/analytics fixtures and responsive tests; main hierarchy corrected without claiming all detail charts identical.');
update('Heatmap/calendar drilldown','53-week Monday grid with minute-based intensity, month labels and right-aligned legend. Stats taps only trained dates; Home calendar opens trained history or untrained date overrides, with monthly totals and markers. Native calendar day surfaces differ.','Trained-only Stats interaction and month totals asserted; duration/streak/date tests and paired Stats/calendar captures.',undefined,undefined,'Stats trained date → history/calendar; Home calendar untrained date → override',undefined,'Stats year intensity by duration and trained-day drilldown; Home calendar can plan untrained dates');
update('Muscle statistics','Independent Cupertino period segments, source All/Hard toggle and by-sets/by-hard-sets heading; relative five-color legend, missed groups, primary 1/secondary .4 effective sets and selectable MIT anatomy. Lower bars/chip layout remains a native adaptation.','Region/effort fixtures, anatomy/selection/responsive tests and paired Stats captures.');
update('Effort statistics','Rated denominator/hard share, RPE/RIR conversion and independent periods; Cupertino segments and primary Top set/e1RM/effort exercise controls aligned. Additional volume/reps/distance metrics are under More progress metrics. Exact lower-chart presentation not paired.','Source-linked effort fixtures and analytics/empty-single-choice/responsive tests.');
update('Plan share/import/PDF','Plan UI exports public openGym v1 routines/week with portable dataset/custom identities, progression/modes/supersets and Sunday 0. Combined native days become explicit exported routines. Preview/merge/replace-week and PDF remain; original SIRVYA API export stays available.','Public-contract fixture and real MySQL compatible export → preview → zero-drop round trip, custom reuse, Sunday, mode/superset and private-data guards; existing import rollback/PDF tests.',accepted,undefined,undefined,'W/workout_home.dart; workout_pdf.dart; B/services/workoutProgram.js; B/routes/anas/workout.js');
update('Workout options','Workout-only options retained; duplicate figure selector removed. Background timer alerts explicitly requests notification/exact-alarm permission; scheduling uses capability-aware exact mode. Native sound/vibration/keep-awake and OS delivery remain unverified.','Preference/reminder tests, clean analysis and release compile. Device checks deferred by user.');
update('Responsive visual system','Neutral surfaces/black text/green accent, bundled font, rounded white chips, Cupertino segments, 34 px scalable page titles, compact metric tiles, root bounded sheets and centered 560 px five-tab bar. Library slivers/calendar scrolling fix landscape and enlarged-text overflow. Home, editor and detail/chart spacing gaps remain.','EN/FR/ES/enlarged-text/landscape checks; all 15 same-fixture capture pairs plus retained-picker captures at 396/1100; no pixel-equality claim.');
update('Personal routine editor','Editable title/progression badge, live autosave/retry, stable IDs, adjacent links, reordering, What this session hits source-map card and retained stacked picker/configuration. Native progression/cards remain taller than source.','Recovery/responsive suites and reviewed editor/configuration/picker pairs.');
update('Minimal custom exercise','Name/body part suffice; optional description and collapsed advanced fields. Private stable identity, duplicate-name guards and immediate selection retained; minimal sheet now has paired evidence.','Custom-flow widgets, MySQL history/ownership/duplicates and matched custom sheet captures.',accepted);
update('Muscle visualization','Same separately MIT-licensed male/female front/back contours and relative five-color Less/More legend. Native SVG parsing/painting and precise hit testing retain region selection in routine, Stats and summary; legacy explorer remains separate.','Four-view geometry/selection and legend tests plus paired Stats/editor/summary artifacts; bundled license/provenance.',accepted);
const rows=old.split(/\r?\n/).filter(l=>l.startsWith('| '));
for(let i=2;i<rows.length;i++){
  const cells=rows[i].split('|').slice(1,-1).map(s=>s.trim());
  const u=updates.get(cells[0]);if(!u)continue;
  if(u.behavior)cells[2]=u.behavior;if(u.visual)cells[3]=u.visual;if(u.flow)cells[4]=u.flow;
  cells[5]=u.implementation;if(u.source)cells[6]=u.source;if(u.status)cells[7]=u.status;cells[8]=u.test;
  rows[i]='| '+cells.join(' | ')+' |';updates.delete(cells[0]);
}
if(updates.size)throw Error('Unmatched rows: '+[...updates.keys()].join(', '));
if(!rows.some(row=>row.startsWith('| Custom exercise deletion |'))){
  rows.push('| Custom exercise deletion | sheets.jsx ExerciseDetail; store/useStore.js deleteCustom | Remove custom exercise from future routines without erasing completed training | Danger confirmation action | Delete → future entries removed; history stays readable | Owner-scoped transaction rejects active-session use; removes only personal future entries, repairs order/supersets and increments revisions, archives stable identity and clears confirmed working load. Coach routines and immutable session snapshots remain intact. | B/routes/anas/workout.js; W/exercise_library.dart | EXACT / ACCEPTABLE PARITY | Real MySQL active-use 409, completed delete 200, personal routine revision/entry cleanup and unchanged historical prescription/volume; deletion confirmation localized EN/FR/ES. |');
}
const counts={};for(const row of rows.slice(2)){const status=row.split('|')[8].trim();counts[status]=(counts[status]??0)+1;}
const intro=`# Current SIRVYA Workout recovery matrix

Reference: [requested openGym](https://github.com/arvids-unavailable/openGym/tree/c42ba6b98e3776af5981f20c05ba392238799670), commit c42ba6b98e3776af5981f20c05ba392238799670. Remote main verified on 2026-10-04; local checkout workout_tmp/requested-reference.

This is the working matrix for the correction. [Previous audit](WORKOUT_PRODUCT_PARITY.md) and its pass counts are historical. Source behavior, visual structure, interactions and verification are assessed separately; dataset identity and passing tests alone do not establish product parity. Scope excludes reference authentication, accounts, general settings and standalone hosting; SIRVYA JWT/users, linked Coach/Client authorization, Flutter, API and MySQL remain the host. Dataset import was not rerun. W/ = lib/screens/ENG/workout/; B/ = backend/.

Final available checks recorded on **2026-10-05**. Assessment: **${rows.length-2} rows: ${counts[accepted]} EXACT / ACCEPTABLE PARITY, ${counts.PARTIAL} PARTIAL, ${counts['BLOCKED - LICENSE']} BLOCKED - LICENSE and 4 excluded**. Accepted native adaptations need matching product behavior and reviewed structure; this is not a pixel-equality or overall completion claim. Most partial rows have implemented behavior but visibly different controls/spacing or outstanding interaction/device evidence.

Checks: backend **81 passed, 3 skipped, 0 failed** (84 total, local MySQL enabled). All thirteen Workout Flutter suites **63 passed, 1 optional legacy capture skipped, 0 failed**; final host-navigation/app smoke **2 passed**. Additional responsive/capture revalidation **14 passed**. Final Workout/host/service/model/localization analysis reports **No issues found**. Raw logs: workout_tmp/recovery-finish-backend.log, recovery-finish-all-flutter.log, recovery-final-responsive.log, recovery-host-final.log and recovery-host-analysis.log. Skip counts are explicit; they are not passes.

The **final release web build passed (163.8 seconds)** after the SIRVYA navigation change. The built-app browser check uses isolated synthetic API fixtures, verifies full-screen Workout entry without host navigation and returns to SIRVYA; it does not prove real-user authentication or physical-device delivery. Report: workout_tmp/recovery-web-smoke.json; capture: [full built app](verification/parity/sirvya-full-web-smoke.png). Local review: http://localhost:8080 with API port 3000; local scheduled outbound Workout reminders are disabled. The existing intro video reports unsupported format in the headless browser; this is a host warning outside the Workout parity scope.

Recovery now includes one-tap weekly/date assignment, calendar totals/markers, compatible openGym v1 export, safe custom-exercise deletion, scalable source-style headers/segments/chips/metrics, root sheets, scrollable library filters, prominent check-in and full-screen host integration. Prior recovery fixes for progression, real previous-load precedence, custom cardio, retained picker, licensed anatomy and persistent media preferences remain intact. [Capture review](verification/parity/README.md) contains all fifteen source/native page/sheet pairs, including the picker, at 396/1100 pixels.

**Still open:** Home/week/weight chart and routine-editor row spacing; guided-workout/detail/lower-statistics presentation; dedicated full picker page-boundary and external training-file UX verification; physical notification/sound/vibration/awake/process-kill checks (no device attached; user selected available checks first). Original full-catalog demonstration coverage is blocked: the [dataset LICENSE media exception](https://github.com/hasaneyldrm/exercises-dataset/blob/main/LICENSE) explicitly excludes Gym Visual images/videos from MIT and requires downstream rights. Reviewed replacement media covers 24 exercise identities; no complete GIF parity is claimed.

`;
fs.writeFileSync(auditPath,intro+rows.join('\n')+'\n');
console.log(JSON.stringify({rows:rows.length-2,counts}));
