-- Workout configuration and durable alerts belong to the existing SIRVYA users.
CREATE TABLE IF NOT EXISTS workout_preferences (
  userID BIGINT UNSIGNED PRIMARY KEY,
  preferences JSON NOT NULL,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userID) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workout_exercise_preferences (
  userID BIGINT UNSIGNED NOT NULL,
  exerciseID BIGINT UNSIGNED NOT NULL,
  favorite TINYINT(1) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  PRIMARY KEY (userID, exerciseID),
  FOREIGN KEY (userID) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (exerciseID) REFERENCES exercises(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workout_schedule (
  userID BIGINT UNSIGNED NOT NULL,
  workoutDate DATE NOT NULL,
  workoutDayID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (userID, workoutDate, workoutDayID),
  FOREIGN KEY (userID) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (workoutDayID) REFERENCES workout_days(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workout_schedule_dates (
  userID BIGINT UNSIGNED NOT NULL,
  workoutDate DATE NOT NULL,
  PRIMARY KEY (userID, workoutDate),
  FOREIGN KEY (userID) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workout_alerts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userID BIGINT UNSIGNED NOT NULL,
  sessionID BIGINT UNSIGNED NULL,
  alertKey VARCHAR(160) NOT NULL,
  dueAt DATETIME NOT NULL,
  title VARCHAR(160) NOT NULL,
  body VARCHAR(500) NOT NULL,
  deliveredAt DATETIME NULL,
  claimedAt DATETIME NULL,
  UNIQUE KEY uq_workout_alert (userID, alertKey),
  KEY idx_workout_alert_due (deliveredAt, dueAt),
  FOREIGN KEY (userID) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (sessionID) REFERENCES workout_sessions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workout_media (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ownerID BIGINT UNSIGNED NOT NULL,
  sessionID BIGINT UNSIGNED NULL,
  exerciseID BIGINT UNSIGNED NULL,
  filename VARCHAR(80) NOT NULL UNIQUE,
  mimeType VARCHAR(80) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(ownerID) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(sessionID) REFERENCES workout_sessions(id) ON DELETE CASCADE,
  FOREIGN KEY(exerciseID) REFERENCES exercises(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workout_imports (
  userID BIGINT UNSIGNED NOT NULL,
  fingerprint CHAR(64) NOT NULL,
  sessionID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY(userID,fingerprint),
  FOREIGN KEY(userID) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(sessionID) REFERENCES workout_sessions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workout_import_exercises (
  userID BIGINT UNSIGNED NOT NULL,
  sourceKey CHAR(64) NOT NULL,
  exerciseID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY(userID,sourceKey),
  FOREIGN KEY(userID) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(exerciseID) REFERENCES exercises(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
