// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMFk_cDAOFAYCY90XWwiapyjBUIdP16q4',
    appId: '1:256158398727:web:71d758851fb56c4ad32da2',
    messagingSenderId: '256158398727',
    projectId: 'sirvya-app',
    authDomain: 'sirvya-app.firebaseapp.com',
    storageBucket: 'sirvya-app.firebasestorage.app',
    measurementId: 'G-NZ0S2YSJ5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN1OEx0nDomRNL0m4xReD6_jdvm0RD0zs',
    appId: '1:256158398727:android:5b036b4132446841d32da2',
    messagingSenderId: '256158398727',
    projectId: 'sirvya-app',
    storageBucket: 'sirvya-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTMIBkN-Oz05Lnj9LN9dNzngxXg-vLRtI',
    appId: '1:256158398727:ios:0eee5788d9d99bacd32da2',
    messagingSenderId: '256158398727',
    projectId: 'sirvya-app',
    storageBucket: 'sirvya-app.firebasestorage.app',
    iosBundleId: 'com.example.fitlek1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTMIBkN-Oz05Lnj9LN9dNzngxXg-vLRtI',
    appId: '1:256158398727:ios:0eee5788d9d99bacd32da2',
    messagingSenderId: '256158398727',
    projectId: 'sirvya-app',
    storageBucket: 'sirvya-app.firebasestorage.app',
    iosBundleId: 'com.example.fitlek1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMFk_cDAOFAYCY90XWwiapyjBUIdP16q4',
    appId: '1:256158398727:web:fe139629bed6257ad32da2',
    messagingSenderId: '256158398727',
    projectId: 'sirvya-app',
    authDomain: 'sirvya-app.firebaseapp.com',
    storageBucket: 'sirvya-app.firebasestorage.app',
    measurementId: 'G-P5RGTTGD8H',
  );
}
